[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools >= 75"]
# requires = ["setuptools>=64", "setuptools_scm>=8"]  # get version directly from git


[project]
name = "srwave"
dynamic = ["version"]
description = "Synchrotron Radiation Wave optics tools"
readme = "README.md"
authors = [
    {name = "Juventino J. Férrer da Fonseca", email = "ferrerjuven@gmail.com"}
]
# maintainers = [{name = "", email = ""}]
requires-python = ">=3.8"
dependencies = [
    "srwpy >= 4.1.0",
    "xraylib >= 4.1.5",
    "optlnls >= 0.3.18",
]
# also required, but installed with srwpy: h5py, matplotlib, numpy, pillow, scikit-learn, scipy
license = {file = "LICENSE"}
# keywords = []
# classifier of status: "Development Status :: 3 - Alpha"
classifiers = [
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Physics",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
dev = [
    # Scripts
    "notebook",
    "PyQt6",
    # Performance
    "line_profiler",
    # PyPI deployment tools
    "build",
    "twine",
]
test = [
    # Linting
    "ruff",
    "black",
    "flake8",
    "isort",
    "mypy",
    # Testing
    "pytest",
]

[project.urls]
# homepage = "not yet"
# documentation = "not yet"
source = "https://github.com/lnls-ids/SR-Wave-optics"
# download = "not yet in PyPI"
tracker = "https://github.com/lnls-ids/SR-Wave-optics/issues"


[tool.setuptools.dynamic]
version = {file = "VERSION"}

# alternative using setuptools-scm
# [tool.setuptools_scm] # just the presence of this tables enables setuptools-scm
# version_file = "pkg/_version.py" # grep version from file, if wanted

